version: "3.8"

services:
  api:
    build: .
    hostname: api
    volumes:
      - ./pprof/api:/pprof
    expose:
      - "8080:8080"
    environment:
      PORT: 8080
      JWT_SECRET: coffe_blend
      DATABASE_URL: "host=host.docker.internal user=admin password=admin port=5432 dbname=gorm"
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
