CREATE TABLE IF NOT EXISTS customers (
    id VARCHAR NOT NULL,
    name VARCHAR(45) NOT NULL,
    phone VARCHAR(14) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    areated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
)