CREATE TABLE IF NOT EXISTS customers (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    phone VARCHAR(14) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
)